language: php
dist: xenial

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly
  
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    
before_install:
  - sudo apt-get install libglfw3
  - sudo apt-get install libglfw3-dev

install:
    - phpize
    - ./configure
    - make
    - make install

before_script:
  - echo "extension=glfw.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini